core/config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  put '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  get '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  get '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv', :as => :cvv
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

core/app/views/spree/admin/shared/_address.html.erb
<p data-hook="address">
  <%="#{address.firstname} #{address.lastname} "%><%= address.company unless address.company.blank? %>
  <%="(#{address.phone}" %><%= address.alternative_phone unless address.alternative_phone.blank? %>)<br />
  <%= address.address1 %> <%= ", #{address.address2}" unless address.address2.blank? %>
  <%= ", #{address.city}, #{address.state_text}, #{address.zipcode}, #{address.country.name}" %>
</p>

core/app/views/spree/admin/shared/_address_form.html.erb
<table class="index">
  <thead>
    <tr data-hook="use_billing">
      <th colspan="8">
        <%= name %>
        <span class="right">
          <% if use_billing %>
            <%= check_box_tag 'order[use_billing]', '1', (!(@order.bill_address.empty? && @order.ship_address.empty?) && @order.bill_address.same_as?(@order.ship_address)) %> 
            <%= label_tag 'order[use_billing]', t(:use_billing_address) %>
          <% end %>
        </span>
      </th>
    </tr>
  </thead>
  <tbody id="<%= name == t(:shipping_address) ? 'shipping' : 'billing' %>" style="display: <%= (use_billing && (!(@order.bill_address.empty? && @order.ship_address.empty?) && @order.bill_address.eql?(@order.ship_address))) ? 'none' : '' %>" data-hook="address_fields">
    <tr class="<%= name == t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :firstname, t(:first_name) + ':' %>
      </td>
      <td class="val-col" colspan="3"><%= f.text_field :firstname %></td>
      <td class="lbl-col">
        <%= f.label :lastname, t(:last_name) + ':' %>
      </td>
      <td class="val-col" colspan="3"><%= f.text_field :lastname %></td>
    </tr>
    <% if Spree::Config[:company] %>
      <tr class="<%= name == t(:company) ? 'shipping-row' : 'billing-row' %>">
        <td class="lbl-col">  <%= f.label :company, t(:company) + ':' %> </td>
        <td class=colspan="7"> <%= f.text_field :company %> </td>
      </tr>
    <% end %>
    <tr class="<%= name == t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :address1, t(:street_address) + ':' %>
      </td>
      <td colspan="3"><%= f.text_field :address1, :class => "fullwidth" %></td>
      <td class="lbl-col">
        <%= f.label :address2, t(:street_address_2) + ':' %>
      </td>
      <td colspan="3"><%= f.text_field :address2, :class => "fullwidth" %></td>
    </tr>
    <tr class="<%= name == t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :city, t(:city) + ':' %>
      </td>
      <td colspan="3"><%= f.text_field :city %></td>
      <td class="lbl-col">
        <%= f.label :zipcode, t(:zip) + ':' %>
      </td>
      <td colspan="3"><%= f.text_field :zipcode, :style => 'width: 100px;' %></td>
    </tr>
    <tr class="<%= name == t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :state_id, t(:state) + ':' %>
      </td>
      <td colspan="3">
        <span id="<%= name == t(:shipping_address) ? 's' : 'b' %>state">

          <%= f.text_field :state_name, :style => "width:150px; display: #{f.object.country.states.empty? ? 'block' : 'none' };", :disabled => !f.object.country.states.empty? %>
          <%= f.collection_select :state_id, f.object.country.states.sort, :id, :name, {:include_blank => true}, {:style => "width:150px; display: #{f.object.country.states.empty? ? 'none' : 'block' };", :disabled => f.object.country.states.empty?} %>
        </span>
      </td>
      <td class="lbl-col">
        <%= f.label :country_id, t(:country) + ':' %>
      </td>
      <td colspan="3">
        <span id="<%= name == t(:shipping_address) ? 's' : 'b' %>country"><%= f.collection_select :country_id, available_countries, :id, :name, {}, {:style => 'width: 150px;'} %></span>
      </td>
    </tr>
    <tr class="<%= name == t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :phone, t(:phone) + ':' %>
      </td>
      <td colspan="7"><%= f.phone_field :phone %></td>
    </tr>
  </tbody>
</table>

<% content_for :head do %>
  <%= javascript_tag do -%>
    $(document).ready(function(){
      $('span#<%= name == t(:shipping_address) ? 's' : 'b' %>country select').change(function() { update_state('<%= name == t(:shipping_address) ? 's' : 'b' %>'); });
    });
  <% end -%>
<% end %>

core/app/views/spree/admin/shared/_alert.html.erb
<div class="alert <%= alert.severity.downcase %>">
  <%= alert.message %> <%= link_to alert.url_name, alert.url if alert.url %>
  <%= link_to 'X', dismiss_alert_admin_general_settings_path(:alert_id => alert.id),
              :remote => true, :method => :post, :class => 'dismiss' %>
</div>

core/app/views/spree/admin/shared/_configuration_menu.html.erb
<% content_for :sidebar do %>

  <h3><%= t(:configurations) %></h3>
  <br class="clear" />

  <ul class="sidebar" data-hook="admin_configurations_sidebar_menu">
    <%= configurations_sidebar_menu_item t(:general_settings), admin_general_settings_path %>
    <%= configurations_sidebar_menu_item t(:mail_methods), admin_mail_methods_path %>
    <%= configurations_sidebar_menu_item t(:tax_categories), admin_tax_categories_path %>
    <%= configurations_sidebar_menu_item t(:zones), admin_zones_path %>
    <%= configurations_sidebar_menu_item t(:states), admin_country_states_path(Spree::Config[:default_country_id]) %>
    <%= configurations_sidebar_menu_item t(:payment_methods), admin_payment_methods_path %>
    <%= configurations_sidebar_menu_item t(:taxonomies), admin_taxonomies_path %>
    <%= configurations_sidebar_menu_item t(:shipping_methods), admin_shipping_methods_path %>
    <%= configurations_sidebar_menu_item t(:inventory_settings), admin_inventory_settings_path %>
    <%= configurations_sidebar_menu_item t(:analytics_trackers), admin_trackers_path %>
  </ul>
  <ul class="sidebar">
    <li id="complete_settings_list"><%= link_to t(:complete_list), admin_configurations_path %>
  </ul>
<% end %>

core/app/views/spree/admin/shared/_destroy.js.erb
notice_div = $('.flash.notice');
<% notice = flash.discard(:notice)
if notice %>
  if (notice_div.length > 0) {
    notice_div.html("<%= notice %>");
    notice_div.show();
  } else {
    if ($("#content .toolbar").length > 0) {
      $("#content .toolbar").before('<div class="flash notice"><%= notice %></div>');
    } else {
      $("#content h1").before('<div class="flash notice"><%= notice %></div>');
    }
  } <%
end %>

<%= render :partial => '/spree/admin/shared/update_order_state' if @order %>

core/app/views/spree/admin/shared/_edit_resource_links.html.erb
<p class="form-buttons" data-hook="buttons">
  <%= button t(:update) %>
  <%= t(:or) %> <%= link_to t(:cancel), collection_url %>
</p>

core/app/views/spree/admin/shared/_new_adjustment_button.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
      <%= button_link_to t(:new_adjustment), new_admin_order_adjustment_url(@order), :icon => 'add' %>
    </li>
  </ul>
  <br class="clear" />
</div>

core/app/views/spree/admin/shared/_order_details.html.erb
<table class="index" data-hook="order_details">
  <tbody id="line-items" data-hook>
    <tr data-hook="order_details_line_items_headers">
      <th><%= t(:item_description) %></th>
      <th class="price"><%= t(:price) %></th>
      <th class="qty"><%= t(:qty) %></th>
      <th class="total"><span><%= t(:total) %></span></th>
    </tr>

    <% @order.line_items.each do |item| %>
      <tr data-hook="order_details_line_item_row">
        <td width="300"><%= item.variant.product.name %> <%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %></td>
        <td class="price"><%= number_to_currency item.price %></td>
        <td class="qty"><%= item.quantity %></td>
        <td class="total"><span><%= number_to_currency (item.price * item.quantity) %></span></td>
      </tr>
    <% end %>
  </tbody>
  <tbody id="subtotal" data-hook="order_details_subtotal">
    <tr class="total" id="subtotal-row">
      <td colspan="3"><b><%= t(:subtotal) %>:</b></td>
      <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
    </tr>
  </tbody>
  <tbody id="order-charges" data-hook="order_details_adjustments">
    <% @order.adjustments.eligible.each do |adjustment| %>
    <% next if (adjustment.originator_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
      <tr class="total">
        <td colspan="3"><strong><%= adjustment.label %></strong></td>
        <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
      </tr>
    <% end %>
  </tbody>
  <tbody id="order-total" data-hook="order_details_total">
    <tr class="total">
      <td colspan="3"><b><%= t(:order_total) %>:</b></td>
      <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
    </tr>
  </tbody>
  <% if order.price_adjustment_totals.present? %>
    <tbody id="price-adjustments" data-hook="order_details_price_adjustments">
      <% @order.price_adjustment_totals.keys.each do |key| %>
        <tr class="total">
          <td colspan="3"><strong><%= key %></strong></td>
          <td class="total"><span><%= number_to_currency @order.price_adjustment_totals[key] %></span></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

core/app/views/spree/admin/shared/_order_tabs.html.erb
<h1><%= t(:order) %> <%= @order.number %></h1>

<% content_for :sidebar do %>
  <div id="order_tab_summary" data-hook>
    <h3 id="order_number" data-hook><%= t(:order) %> #<%= @order.number%></h3>
    <h5 id="order_status" data-hook><%= t(:status) %>: <%= t(@order.state, :scope => :order_state) %></h5>
    <h5 id="order_total" data-hook><%= t(:total) %>: <%= number_to_currency @order.total %></h5>
    <% if @order.completed? %>
      <h5 id="shipment_status"><%= t(:shipment) %>: <%= t(@order.shipment_state, :scope => :shipment_state, :default => [:missing, "none"]) %></h5>
      <h5 id="payment_status"><%= t(:payment) %>: <%= t(@order.payment_state, :scope => :payment_states, :default => [:missing, "none"]) %></h5>
    <% end %>
    <br class="clear" />
  </div>
  <br class="clear" />

  <ul class="sidebar" data-hook="admin_order_tabs">
    <% unless @order.completed? %>
      <li<%== ' class="active"' if current == 'Order Details' %>>
        <%= link_to t(:order_details), edit_admin_order_url(@order) %>
      </li>
      <li<%== ' class="active"' if current == 'Customer Details' %>>
          <%= link_to t(:customer_details), admin_order_customer_url(@order) %>
      </li>
      <li<%== ' class="active"' if current == 'Shipments' %>>
         <%= link_to t(:shipment), @order.line_items.empty? || !@order.completed? ? 'javascript:$("form").submit();' : edit_admin_order_shipment_url(@order, @order.shipment) %>
      </li>
      <li<%== ' class="active"' if current == 'Adjustments' %>>
         <%= link_to t(:adjustments), @order.line_items.empty? || !@order.completed? ? 'javascript:$("form").submit();' : admin_order_adjustments_url(@order) %>
      </li>
      <li<%== ' class="active"' if current == 'Payments' %>>
         <%= link_to t(:payment), @order.line_items.empty? || !@order.completed? ? 'javascript:$("form").submit();' : new_admin_order_payment_url(@order) %>
      </li>

    <% else %>
      <li<%== ' class="active"' if current == 'Order Details' %>>
        <%= link_to t(:order_details), admin_order_url(@order) %>
      </li>
      <li<%== ' class="active"' if current == 'Customer Details' %>>
        <%= link_to t(:customer_details), admin_order_customer_url(@order) %>
      </li>
      <li<%== ' class="active"' if current == 'Adjustments' %>>
         <%= link_to t(:adjustments), admin_order_adjustments_url(@order) %>
      </li>
      <li<%== ' class="active"' if current == 'Payments' %>>
         <%= link_to t(:payments), admin_order_payments_url(@order) %>
      </li>
      <li<%== ' class="active"' if current == 'Shipments' %>>
         <%= link_to t(:shipments), admin_order_shipments_url(@order) %>
      </li>
      <li<%== ' class="active"' if current == 'Return Authorizations' %>>
         <%= link_to t(:return_authorizations), admin_order_return_authorizations_url(@order) %>
      </li>
    <% end %>
  </ul>

<% end %>

core/app/views/spree/admin/shared/_product_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav" data-hook="admin_product_sub_tabs">
    <%= tab :products, :match_path => '/products' %>
    <%= tab :option_types, :match_path => '/option_types' %>
    <%= tab :properties %>
    <%= tab :prototypes %>
  </ul>
<% end %>

core/app/views/spree/admin/shared/_product_tabs.html.erb
<h1><%= t(:editing_product) %> &ldquo;<%= @product.name %>&rdquo;</h1>

<% content_for :sidebar do %>

  <h3><%= @product.name %><span class="sku"><%= @product.sku %></span></h3>
  <br class="clear" />

  <ul class="sidebar product-menu" data-hook="admin_product_tabs">
    <li<%== ' class="active"' if current == 'Product Details' %>>
      <%= link_to t(:product_details), edit_admin_product_url(@product) %>
    </li>
    <li<%== ' class="active"' if current == 'Images' %>>
      <%= link_to t(:images), admin_product_images_url(@product) %>
    </li>
    <li<%== ' class="active"' if current == 'Variants' %>>
      <%= link_to t(:variants),  admin_product_variants_url(@product) %>
    </li>
    <li<%== ' class="active"' if current == 'Product Properties' %>>
      <%= link_to t(:product_properties), admin_product_product_properties_url(@product) %>
    </li>
  </ul>
  <br class="clear" />

<% end %>

core/app/views/spree/admin/shared/_report_criteria.html.erb
<%= search_form_for @search, :url => spree.sales_total_admin_reports_path  do |s| %>
    <%= label_tag nil, t(:date_range) %><br />
    <div class="date-range-filter">
      <div class="left sub-field">
        <%= s.text_field :created_at_gt, :class => 'datepicker' %><br />
        <%= label_tag nil, t(:start), :class => 'sub' %>
      </div>
      <div class="right sub-field">
        <%= s.text_field :created_at_lt, :class => 'datepicker' %><br />
        <%= label_tag nil, t(:stop) %>
      </div>
    </div>

    <p><%= button t(:search) %></p>
<% end %>

core/app/views/spree/admin/shared/_show_resource_links.html.erb
<p class="actions" data-hook="actions">
  <%= link_to t(:edit), edit_object_url %> |
  <%= link_to t(:back), collection_url %> |
  <%= link_to t(:delete), object_url, :method => :delete, :data => { :confirm => t(:are_you_sure_you_want_to_delete_this_record) } %>
</p>