core/config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  put '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  get '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  get '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv', :as => :cvv
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

core/app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

core/app/models/spree/ability.rb
# Implementation class for Cancan gem.  Instead of overriding this class, consider adding new permissions
# using the special +register_ability+ method which allows extensions to add their own abilities.
#
# See http://github.com/ryanb/cancan for more details on cancan.
require 'cancan'
module Spree
  class Ability
    include CanCan::Ability

    class_attribute :abilities
    self.abilities = Set.new

    # Allows us to go beyond the standard cancan initialize method which makes it difficult for engines to
    # modify the default +Ability+ of an application.  The +ability+ argument must be a class that includes
    # the +CanCan::Ability+ module.  The registered ability should behave properly as a stand-alone class
    # and therefore should be easy to test in isolation.
    def self.register_ability(ability)
      self.abilities.add(ability)
    end

    def self.remove_ability(ability)
      self.abilities.delete(ability)
    end

    def initialize(user)
      self.clear_aliased_actions

      # override cancan default aliasing (we don't want to differentiate between read and index)
      alias_action :edit, :to => :update
      alias_action :new, :to => :create
      alias_action :new_action, :to => :create
      alias_action :show, :to => :read

      user ||= Spree.user_class.new
      if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')
        can :manage, :all
      else
        #############################
        can :read, User do |resource|
          resource == user
        end
        can :update, User do |resource|
          resource == user
        end
        can :create, User
        #############################
        can :read, Order do |order, token|
          order.user == user || order.token && token == order.token
        end
        can :update, Order do |order, token|
          order.user == user || order.token && token == order.token
        end
        can :create, Order
        #############################
        can :read, Product
        can :index, Product
        #############################
        can :read, Taxon
        can :index, Taxon
        #############################
      end

      #include any abilities registered by extensions, etc.
      Ability.abilities.each do |clazz|
        ability = clazz.send(:new, user)
        @rules = rules + ability.send(:rules)
      end
    end
  end
end

core/app/models/spree/activator.rb
module Spree
  class Activator < ActiveRecord::Base
    cattr_accessor :event_names

    self.event_names = [
      'spree.cart.add',
      'spree.order.contents_changed',
      'spree.user.signup'
    ]

    def self.register_event_name(name)
      self.event_names << name
    end

    scope :event_name_starts_with, lambda{ |name| where('event_name LIKE ?', "#{name}%") }

    def self.active
      where('(starts_at IS NULL OR starts_at < ?) AND (expires_at IS NULL OR expires_at > ?)', Time.now, Time.now)
    end

    def activate(payload)
    end

    def expired?
      starts_at && Time.now < starts_at ||
      expires_at && Time.now > expires_at
    end
  end
end

core/app/models/spree/address.rb
module Spree
  class Address < ActiveRecord::Base
    belongs_to :country
    belongs_to :state

    has_many :shipments

    validates :firstname, :lastname, :address1, :city, :zipcode, :country, :phone, :presence => true
    validate :state_validate

    attr_accessible :firstname, :lastname, :address1, :address2,
                    :city, :zipcode, :country_id, :state_id,
                    :country, :state, :phone, :state_name,
                    :company, :alternative_phone

    # Disconnected since there's no code to display error messages yet OR matching client-side validation
    def phone_validate
      return if phone.blank?
      n_digits = phone.scan(/[0-9]/).size
      valid_chars = (phone =~ /^[-+()\/\s\d]+$/)
      errors.add :phone, :invalid unless (n_digits > 5 && valid_chars)
    end

    def self.default
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new({:country => country}, :without_protection => true)
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.nil? ? state_name : (state.abbr.blank? ? state.name : state.abbr)
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at', 'order_id') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
        :name => full_name,
        :address1 => address1,
        :address2 => address2,
        :city => city,
        :state => state_text,
        :zip => zipcode,
        :country => country.try(:iso),
        :phone => phone
      }
    end

    private

      def state_validate
        # Skip state validation without country (also required)
        # or when disabled by preference
        return if country.blank? || !Spree::Config[:address_requires_state]

        # ensure associated state belongs to country
        if state.present?
          if state.country == country
            self.state_name = nil #not required as we have a valid state and country combo
          else
            if state_name.present?
              self.state = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
        if state_name.present?
          if country.states.present?
            states = country.states.find_all_by_name_or_abbr(state_name)

            if states.size == 1
              self.state = states.first
              self.state_name = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure at least one state field is populated
        errors.add :state, :blank if state.blank? && state_name.blank?
      end

  end
end

core/app/models/spree/adjustment.rb
# Adjustments represent a change to the +item_total+ of an Order.  Each adjustment has an +amount+ that be either
# positive or negative.  Adjustments have two useful boolean flags
#
# +mandatory+
#
# If this flag is set to true then it means the the charge is required and will not be removed from the
# order, even if the amount is zero.  In other words a record will be created even if the amount is zero.
# This is  useful for representing things such as shipping and tax charges where you may want to make it explicitly
# clear that no charge was made for such things.
#
# +locked+
#
# The charge is never to be udpated.  Typically you would want to freeze certain adjustments after checkout.
# One use case for this is if you want to lock a shipping adjustment so that its value does not change
# in the future when making other trivial edits to the order (like an email change).
#
# +eligible?+
#
#  This boolean attributes stores whether this adjustment is currently eligible for its order. Only eligible
#  adjustments count towards the order's adjustment total. This allows an adjustment to be preserved if it
#  becomes ineligible so it might be reinstated.
#
module Spree
  class Adjustment < ActiveRecord::Base
    attr_accessible :amount, :label

    belongs_to :adjustable, :polymorphic => true
    belongs_to :source, :polymorphic => true
    belongs_to :originator, :polymorphic => true

    validates :label, :presence => true
    validates :amount, :numericality => true

    after_save :update_adjustable
    after_destroy :update_adjustable

    # Update the boolean _eligible_ attribute which deterimes which adjustments count towards the order's
    # adjustment_total.
    def set_eligibility
      update_attribute_without_callbacks(:eligible,
                                         mandatory ||
                                         (amount != 0 && eligible_for_originator?))
    end

    # Allow originator of the adjustment to perform an additional eligibility of the adjustment
    # Should return _true_ if originator is absent or doesn't implement _eligible?_
    def eligible_for_originator?
      return true if originator.nil?
      !originator.respond_to?(:eligible?) || originator.eligible?(source)
    end

    # Update both the eligibility and amount of the adjustment. Adjustments delegate updating of amount to their Originator
    # when present, but only if +locked+ is false.  Adjustments that are +locked+ will never change their amount.
    # The new adjustment amount will be set by by the +originator+ and is not automatically saved.  This makes it save
    # to use this method in an after_save hook for other models without causing an infinite recursion problem.
    #
    # order#update_adjustments passes self as the src, this is so calculations can be performed on the
    # current values. If we used source it would load the old record from db for the association
    def update!(src = nil)
      src ||= source
      return if locked?
      if originator.present?
        originator.update_adjustment(self, src)
      end
      set_eligibility
    end

    private

      def update_adjustable
        adjustable.update! if adjustable.is_a? Order
      end

      class << self
        def tax
          where(:originator_type => 'Spree::TaxRate', :adjustable_type => 'Spree::Order')
        end

        def price
          where(:adjustable_type => 'Spree::LineItem')
        end

        def shipping
          where(:originator_type => 'Spree::ShippingMethod')
        end

        def optional
          where(:mandatory => false)
        end

        def eligible
          where(:eligible => true)
        end

        def charge
          where('amount >= 0')
        end

        def credit
          where('amount < 0')
        end
      end

  end
end

core/app/models/spree/alert.rb
module Spree
  class Alert < ActiveResource::Base
    self.site = 'http://alerts.spreecommerce.com/'
    self.format = :json

    def self.current(host)
      find(:all, :params => { :version => Spree.version,
                              :name => Spree::Config[:site_name],
                              :host => host,
                              :rails_env => Rails.env,
                              :rails_version => Rails.version })
    end
  end
end

core/app/models/spree/asset.rb
module Spree
  class Asset < ActiveRecord::Base
    belongs_to :viewable, :polymorphic => true
    acts_as_list :scope => :viewable
  end
end

core/app/models/spree/billing_integration.rb
module Spree
  class BillingIntegration < PaymentMethod
    validates :name, :presence => true

    preference :server, :string, :default => 'test'
    preference :test_mode, :boolean, :default => true

    def provider
      integration_options = options
      ActiveMerchant::Billing::Base.integration_mode = integration_options[:server].to_sym
      integration_options = options
      integration_options[:test] = true if integration_options[:test_mode]
      @provider ||= provider_class.new(integration_options)
    end

    def options
      options_hash = {}
      self.preferences.each do |key,value|
        options_hash[key.to_sym] = value
      end
      options_hash
    end
  end
end

core/app/models/spree/calculator.rb
module Spree
  class Calculator < ActiveRecord::Base
    belongs_to :calculable, :polymorphic => true

    # This method must be overriden in concrete calculator.
    #
    # It should return amount computed based on #calculable and/or optional parameter
    def compute(something=nil)
      raise(NotImplementedError, 'please use concrete calculator')
    end

    # overwrite to provide description for your calculators
    def self.description
      'Base Calculator'
    end

    ###################################################################

    def self.register(*klasses)
    end

    # Returns all calculators applicable for kind of work
    def self.calculators
      Rails.application.config.spree.calculators.all
    end

    def to_s
      self.class.name.titleize.gsub("Calculator\/", "")
    end

    def description
      self.class.description
    end

    def available?(object)
      true
    end
  end
end

core/app/models/spree/calculator/flat_percent_item_total.rb
require_dependency 'spree/calculator'

module Spree
  class Calculator::FlatPercentItemTotal < Calculator
    preference :flat_percent, :decimal, :default => 0

    attr_accessible :preferred_flat_percent

    def self.description
      I18n.t(:flat_percent)
    end

    def compute(object)
      return unless object.present? and object.line_items.present?
      item_total = object.line_items.map(&:amount).sum
      value = item_total * BigDecimal(self.preferred_flat_percent.to_s) / 100.0
      (value * 100).round.to_f / 100
    end
  end
end

core/app/models/spree/calculator/flat_rate.rb
require_dependency 'spree/calculator'

module Spree
  class Calculator::FlatRate < Calculator
    preference :amount, :decimal, :default => 0
    attr_accessible :preferred_amount

    def self.description
      I18n.t(:flat_rate_per_order)
    end

    def compute(object=nil)
      self.preferred_amount
    end
  end
end

core/app/views/spree/shared/_error_messages.html.erb
<% if target && target.errors.any? %>
  <div id="errorExplanation" class="errorExplanation" data-hook>
    <h2><%= t(:errors_prohibited_this_record_from_being_saved, :count => target.errors.count) %>:</h2>
    <p><%= t(:there_were_problems_with_the_following_fields) %>:</p>
     <ul>
     <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

core/app/views/spree/shared/_filters.html.erb
<% filters = @taxon ? @taxon.applicable_filters : [Spree::ProductFilters.all_taxons] %>
<% unless filters.empty? %>
  <%= form_tag '', :method => :get, :id => 'sidebar_products_search' do %>
    <% params[:search] ||= {} %>
    <%= hidden_field_tag 'per_page', params[:per_page] %>
    <% filters.each do |filter| %>
      <% labels = filter[:labels] || filter[:conds].map {|m,c| [m,m]} %>
      <% next if labels.empty? %>
      <div class="navigation" data-hook="navigation">
        <h6 class="filter-title"> <%= filter[:name] %> </h6>
        <ul class="filter_choices">
          <% labels.each do |nm,val| %>
            <% label = "#{filter[:name]}_#{nm}".gsub(/\s+/,'_') %>
            <li class="nowrap">
              <input type="checkbox"
                     id="<%= label %>"
                     name="search[<%= filter[:scope].to_s %>][]"
                     value="<%= val %>"
                     <%= params[:search][filter[:scope]] && params[:search][filter[:scope]].include?(val.to_s) ? "checked" : "" %> />
              <label class="nowrap" for="<%= label %>"> <%= nm %> </label>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= submit_tag t(:search), :name => nil %>
  <% end %>
<% end %>

core/app/views/spree/shared/_footer.html.erb
<footer id="footer" class="alpha omega sixteen columns" data-hook>
  <div id="footer-left" class="columns alpha eight" data-hook>
    <p><%= t :powered_by  %> <%= link_to 'Spree', 'http://spreecommerce.com/' %></p>
  </div>
  <div id="footer-right" class="columns omega eight" data-hook></div>
</footer>

core/app/views/spree/shared/_google_analytics.html.erb
<% if tracker = Spree::Tracker.current %>

  <%= javascript_tag do %>
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '<%= tracker.analytics_id %>']);
    _gaq.push(['_trackPageview']);

    <% if flash[:commerce_tracking] %>
      // report e-commerce transaction information when applicable
      _gaq.push(['_addTrans',
        "<%= @order.number %>",                            // Order Number
        "",                                                // Affiliation
        "<%= @order.total %>",                             // Order total
        "<%= @order.adjustments.tax.sum(:amount) %>",      // Tax Amount
        "<%= @order.adjustments.shipping.sum(:amount) %>", // Ship Amount
        "",                                                // City
        "",                                                // State
        ""                                                 // Country
      ]);
      <% @order.line_items.each do |line_item| %>
        _gaq.push(['_addItem',
          "<%= @order.number %>",                  // order ID - required
          "<%= line_item.variant.sku %>",          // SKU/code - required
          "<%= line_item.variant.product.name %>", // product name
          "",                                      // category or variation, Product Category
          "<%= line_item.price %>",                // unit price - required
          "<%= line_item.quantity %>"              // quantity - required
        ]);
      <% end %>
    <% end %>

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  <% end %>
<% end %>

core/app/views/spree/shared/_head.html.erb
<meta charset="utf-8">
<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><%= title %></title>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">
<%== meta_data_tags %>
<%= favicon_link_tag image_path('favicon.ico') %>
<%= stylesheet_link_tag 'store/all', :media => 'screen' %>
<%= csrf_meta_tags %>
<%= javascript_include_tag 'store/all' %>
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6/html5shiv.min.js"></script>
<![endif]-->
<%= yield :head %>

core/app/views/spree/shared/_header.html.erb
<header id="header" class="row" data-hook>
  <figure id="logo" class="columns alpha six" data-hook><%= logo %></figure>
  <%= render :partial => 'spree/shared/nav_bar' %>
  <%= render :partial => 'spree/shared/main_nav_bar' if store_menu? %>
</header>

core/app/views/spree/shared/_main_nav_bar.html.erb
<nav class="columns alpha omega sixteen">
  <ul id="main-nav-bar" class="inline" data-hook>
    <li id="home-link" data-hook><%= link_to t(:home), root_path %></li>
    <li id="link-to-cart" data-hook><%= link_to_cart %></li>
  </ul>
</nav>

core/app/views/spree/shared/_nav_bar.html.erb
<nav id="top-nav-bar" class="columns omega ten">
  <ul id="nav-bar" class="inline" data-hook>
    <li id="search-bar" data-hook>
      <%= render :partial => 'spree/shared/search' %>
    </li>
  </ul>
</nav>

core/app/views/spree/shared/_order_details.html.erb
<div class="row steps-data">
  
  <div class="columns alpha four">
    <h6><%= t(:shipping_address) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:address) unless @order.completed? %></h6>
    <div class="address">
      <%= order.ship_address %>
    </div>
  </div>

  <div class="columns alpha four">
    <h6><%= t(:billing_address) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:address) unless @order.completed? %></h6>
    <div class="address">
      <%= order.bill_address %>
    </div>
  </div>

  <div class="columns alpha four">
    <h6><%= t(:shipping_method) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:delivery) unless @order.completed? %></h6>
    <div class="delivery">
      <%= order.shipping_method.name %>
    </div>
  </div>

  <div class="columns omega four">
    <h6><%= t(:payment_information) %> <%= link_to "(#{t(:edit)})", checkout_state_path(:payment) unless @order.completed? %></h6>
    <div class="payment-info">
      <% unless order.credit_cards.empty? %>
        <span class="cc-type">
          <%= image_tag "credit_cards/icons/#{order.credit_cards.first.cc_type}.png" %>
          <%= t(:ending_in)%> <%= order.credit_cards.first.last_digits %>
        </span>
        <br />
        <span class="full-name">
          <%= order.credit_cards.first.first_name %>
          <%= order.credit_cards.first.last_name %>
        </span>
      <% end %>
    </div>
  </div>

</div>

<hr />

<table class="index columns alpha omega sixteen" data-hook="order_details">
  <col width="15%" valign="middle" halign="center">
  <col width="70%" valign="middle">
  <col width="5%" valign="middle" halign="center">
  <col width="5%" valign="middle" halign="center">
  <col width="5%" valign="middle" halign="center">

  <thead id="line-items" data-hook>
    <tr data-hook="order_details_line_items_headers">
      <th colspan="2"><%= t(:item) %></th>
      <th class="price"><%= t(:price) %></th>
      <th class="qty"><%= t(:qty) %></th>
      <th class="total"><span><%= t(:total) %></span></th>
    </tr>
  </thead>

  <tbody id="line-items" data-hook>
    <% @order.line_items.each do |item| %>
      <tr data-hook="order_details_line_item_row">
        <td data-hook="order_item_image">
          <% if item.variant.images.length == 0 %>
            <%= link_to small_image(item.variant.product), item.variant.product %>
          <% else %>
            <%= link_to image_tag(item.variant.images.first.attachment.url(:small)), item.variant.product %>
          <% end %>
        </td>
        <td data-hook="order_item_description">
          <h4><%= item.variant.product.name %></h4>
          <%= truncate(item.variant.product.description, :length => 100, :omission => "...") %>
          <%= "(" + variant_options(item.variant) + ")" unless item.variant .option_values.empty? %>
        </td>
        <td data-hook="order_item_price" class="price"><span><%= number_to_currency item.price %></span></td>
        <td data-hook="order_item_qty"><%= item.quantity %></td>
        <td data-hook="order_item_total" class="total"><span><%= number_to_currency (item.price * item.quantity) %></span></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot id="order-total" data-hook="order_details_total">
    <tr class="total">
      <td colspan="4"><b><%= t(:order_total) %>:</b></td>
      <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
    </tr>
  </tfoot>
  <% if order.price_adjustment_totals.present? %>
    <tfoot id="price-adjustments" data-hook="order_details_price_adjustments">
      <% @order.price_adjustment_totals.keys.each do |key| %>
        <tr class="total">
          <td colspan="4"><strong><%= key %></strong></td>
          <td class="total"><span><%= number_to_currency @order.price_adjustment_totals[key] %></span></td>
        </tr>
      <% end %>
    </tfoot>
  <% end %>
  <tfoot id="subtotal" data-hook="order_details_subtotal">
    <tr class="total" id="subtotal-row">
      <td colspan="4"><b><%= t(:subtotal) %>:</b></td>
      <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
    </tr>
  </tfoot>
  <tfoot id="order-charges" data-hook="order_details_adjustments">
    <% @order.adjustments.eligible.each do |adjustment| %>
    <% next if (adjustment.originator_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
      <tr class="total">
        <td colspan="4"><strong><%= adjustment.label %></strong></td>
        <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
      </tr>
    <% end %>
  </tfoot>
</table>

core/app/views/spree/shared/_products.html.erb
<%
  paginated_products = @searcher.retrieve_products if params.key?(:keywords)
  paginated_products ||= products
%>
<% if products.empty? %>
  <%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h6 class="search-results-title"><%= t(:search_results, :keywords => h(params[:keywords])) %></h6>
<% end %>

<% if products.any? %>
<ul id="products" class="inline product-listing" data-hook>
  <% reset_cycle('default') %>
  <% products.each do |product| %>
    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
      <li id="product_<%= product.id %>" class="columns three <%= cycle("alpha", "secondary", "", "omega secondary", :name => "classes") %>" data-hook="products_list_item" itemscope itemtype="http://schema.org/Product">
        <div class="product-image">
          <%= link_to small_image(product, :itemprop => "image"), product, :itemprop => 'url' %>
        </div>
        <%= link_to truncate(product.name, :length => 50), product, :class => 'info', :itemprop => "name", :title => product.name %>
        <span class="price selling" itemprop="price"><%= number_to_currency product.price %></span>
      </li>
    <% end %>
  <% end %>
  <% reset_cycle("classes") %>
</ul>
<% end %>

<% if paginated_products.respond_to?(:num_pages) %>
  <%= paginate paginated_products %>
<% end %>

core/app/views/spree/shared/_search.html.erb
<% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Spree::Taxon.roots %>
<%= form_tag products_path, :method => :get do %>
  <%= select_tag :taxon,
        options_for_select([[t(:all_departments), '']] +
                              @taxons.map {|t| [t.name, t.id]},
                            @taxon ? @taxon.id : params[:taxon]) %>
  <%= search_field_tag :keywords, params[:keywords], :placeholder => t(:search) %>
  <%= submit_tag t(:search), :name => nil %>
<% end %>

core/app/views/spree/shared/_sidebar.html.erb
<aside id="sidebar" class="columns alpha four" data-hook>
  <%= yield :sidebar %>
</aside>

core/app/views/spree/shared/_taxonomies.html.erb
<nav id="taxonomies" class="sidebar-item" data-hook>
  <% get_taxonomies.each do |taxonomy| %>
    <h6 class='taxonomy-root'><%= t(:shop_by_taxonomy, :taxonomy => taxonomy.name.singularize) %></h6>
    <%= taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
  <% end %>
</nav>